#!/bin/sh

eval "$(cat -- "$STARTUP_CONFIG")"
xrdb "$X11_CONFIG/xresources"

xset r rate "200" "30"
xsetroot -cursor_name "left_ptr"

lxsession &
sxhkd &
wali &
picom --experimental-backends &
lemonblocks &

exec bspwm
