#!/bin/sh

eval "$(cat -- "$DISPLAY_CONFIG")"
xrdb "$XRDB_CONFIG"

xset r rate "200" "30"
xsetroot -cursor_name "left_ptr"

lxsession &
sxhkd &
wali &
picom --experimental-backends &
lemonblocks &
dunst &

bspwm
