require("general.utils")
require("general.options")
require("general.keymaps")
require("general.icons")
require("general.plugins")

require("plugins.package")
require("plugins.theme")
require("plugins.core")
require("plugins.navigation")
require("plugins.layout")
require("plugins.analysis")
require("plugins.snippet")
require("plugins.intellisense")
require("plugins.completion")
