require("after.general.helpers")
require("after.general.options")
require("after.general.keymaps")
require("after.general.symbols")
require("after.general.plugins")

require("after.plugins.pacman")
require("after.plugins.core")
require("after.plugins.theme")
require("after.plugins.window")
require("after.plugins.component")
require("after.plugins.highlight")
require("after.plugins.snippet")
require("after.plugins.intellisense")
require("after.plugins.completion")
require("after.plugins.utility")
