require("general.helpers")
require("general.options")
require("general.keymaps")
require("general.symbols")
require("general.plugins")

require("plugins.package")
require("plugins.theme")
require("plugins.core")
require("plugins.control")
require("plugins.navigation")
require("plugins.layout")
require("plugins.highlight")
require("plugins.snippet")
require("plugins.intellisense")
require("plugins.completion")
