#!/bin/sh

bspc monitor --reset-desktops "1" "2" "3" "4" "5" "6" "7" "8" "9"

bspc config automatic_scheme "alternate"
bspc config initial_polarity "second_child"
bspc config focus_follows_pointer "true"

bspc config window_gap "$(xrdb -get "bspwm.gap")"
bspc config border_width "$(xrdb -get "bspwm.border")"
bspc config normal_border_color "$(xrdb -get "bspwm.border_nrm")"
bspc config focused_border_color "$(xrdb -get "bspwm.border_sel")"

bspc subscribe "desktop_focus" "node_add" "node_remove" "node_transfer" |
	while read -r _; do
		killall --signal="USR1" -- "flexblocks"
	done &
