#!/bin/sh

bspc monitor --reset-desktops "一" "二" "三" "四" "五" "六" "七" "八" "九"

bspc config automatic_scheme "alternate"
bspc config initial_polarity "second_child"
bspc config focus_follows_pointer "true"

bspc config top_padding "$(($(xrdb -get "bspwm.padding") + $(xrdb -get "bspwm.gap") + $(xrdb -get "flexblocks.height")))"
bspc config right_padding "$(xrdb -get "bspwm.padding")"
bspc config bottom_padding "$(xrdb -get "bspwm.padding")"
bspc config left_padding "$(xrdb -get "bspwm.padding")"
bspc config window_gap "$(xrdb -get "bspwm.gap")"

bspc config border_width "$(xrdb -get "bspwm.border")"
bspc config normal_border_color "$(xrdb -get "bspwm.border_nrm")"
bspc config focused_border_color "$(xrdb -get "bspwm.border_sel")"

bspc subscribe "desktop_focus" "node_add" "node_remove" "node_transfer" | while read -r _; do killall -10 -- "flexblocks"; done &
