#!/bin/sh

bspc monitor --reset-desktops "1" "2" "3" "4" "5" "6" "7" "8" "9"

bspc config automatic_scheme "alternate"
bspc config initial_polarity "second_child"
bspc config focus_follows_pointer "true"

bspc config window_gap "8"
bspc config border_width "0"
