vim.g.icons = {
  layout = {
    Separator = "•",
    SectionLeft = "",
    SectionRight = "",
  },
  widget = {
    Collapsed = "",
    Expanded = "",
    Search = "",
    Caret = "",
    Tag = "",
    Brand = "",
    Indent = "",
  },
  package = {
    Pending = "",
    Uninstalled = "",
    Installed = "",
    Ready = "",
  },
  document = {
    File = "",
    Link = "",
    Folder = "",
    Open = "",
    Empty = "",
    EmptyOpen = "",
  },
  git = {
    Untracked = "?",
    Added = "+",
    Modified = "!",
    Renamed = "~",
    Deleted = "-",
    Unmerged = "=",
    Ignored = "#",
  },
  space = {
    Tab = "→",
    Trail = "·",
  },
  diagnostic = {
    Suggestion = "",
    Information = "",
    Warning = "",
    Error = "",
  },
  kind = {
    Text = "",
    Unit = "",
    Value = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    Reference = "",
    Folder = "",
    File = "",
    Module = "",
    Namespace = "",
    Package = "",
    Class = "",
    Method = "",
    Property = "",
    Field = "",
    Constructor = "",
    Enum = "",
    Interface = "",
    Function = "",
    Variable = "",
    Constant = "",
    String = "",
    Number = "",
    Boolean = "",
    Array = "",
    Object = "",
    Key = "",
    Null = "",
    EnumMember = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
    Macro = "",
  },
}
