local devicons = require("nvim-web-devicons")
local tokyonight = require("tokyonight")

devicons.setup({
  default = true,
})

tokyonight.colorscheme()

vim.api.nvim_set_hl(0, "NavicText", { link = "Normal" })
vim.api.nvim_set_hl(0, "NavicSeparator", { link = "Conceal" })
vim.api.nvim_set_hl(0, "NavicIconsFile", { link = "CmpItemKindFile" })
vim.api.nvim_set_hl(0, "NavicIconsPackage", { link = "CmpItemKindFolder" })
vim.api.nvim_set_hl(0, "NavicIconsModule", { link = "CmpItemKindModule" })
vim.api.nvim_set_hl(0, "NavicIconsNamespace", { link = "CmpItemKindModule" })
vim.api.nvim_set_hl(0, "NavicIconsClass", { link = "CmpItemKindClass" })
vim.api.nvim_set_hl(0, "NavicIconsConstructor", { link = "CmpItemKindConstructor" })
vim.api.nvim_set_hl(0, "NavicIconsField", { link = "CmpItemKindField" })
vim.api.nvim_set_hl(0, "NavicIconsProperty", { link = "CmpItemKindProperty" })
vim.api.nvim_set_hl(0, "NavicIconsMethod", { link = "CmpItemKindMethod" })
vim.api.nvim_set_hl(0, "NavicIconsStruct", { link = "CmpItemKindStruct" })
vim.api.nvim_set_hl(0, "NavicIconsEvent", { link = "CmpItemKindEvent" })
vim.api.nvim_set_hl(0, "NavicIconsInterface", { link = "CmpItemKindInterface" })
vim.api.nvim_set_hl(0, "NavicIconsEnum", { link = "CmpItemKindEnum" })
vim.api.nvim_set_hl(0, "NavicIconsEnumMember", { link = "CmpItemKindEnumMember" })
vim.api.nvim_set_hl(0, "NavicIconsConstant", { link = "CmpItemKindConstant" })
vim.api.nvim_set_hl(0, "NavicIconsFunction", { link = "CmpItemKindFunction" })
vim.api.nvim_set_hl(0, "NavicIconsTypeParameter", { link = "CmpItemKindTypeParameter" })
vim.api.nvim_set_hl(0, "NavicIconsVariable", { link = "CmpItemKindVariable" })
vim.api.nvim_set_hl(0, "NavicIconsOperator", { link = "CmpItemKindOperator" })
vim.api.nvim_set_hl(0, "NavicIconsNull", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsBoolean", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsNumber", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsString", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsKey", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsArray", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsObject", { link = "CmpItemKindValue" })
