_G.icons = {
  ui = {
    Collapsed = "",
    Expanded = "",
    Modified = "●",
    Pending = "",
    Uninstalled = "",
    Installed = "",
    SectionLeft = "",
    SectionRight = "",
  },
  document = {
    File = "",
    Link = "",
    Folder = "",
    Open = "",
    Empty = "",
    EmptyOpen = "",
  },
  git = {
    Untracked = "?",
    Added = "+",
    Modified = "!",
    Renamed = "~",
    Deleted = "-",
    Unmerged = "=",
    Ignored = "#",
  },
  diagnostic = {
    Error = "",
    Warn = "",
    Hint = "",
    Info = "",
  },
  kind = {
    File = "",
    Folder = "",
    Module = "",
    Reference = "",
    Class = "",
    Constructor = "",
    Field = "",
    Property = "",
    Method = "",
    Struct = "",
    Event = "",
    Interface = "",
    Enum = "",
    EnumMember = "",
    Constant = "",
    Function = "",
    TypeParameter = "",
    Variable = "",
    Value = "",
    Keyword = "",
    Unit = "",
    Operator = "",
    Color = "",
    Snippet = "",
    Text = "",
  },
  type = {
    Null = "",
    Boolean = "",
    Number = "",
    String = "",
    Array = "",
    Object = "",
  },
}
